/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as SwimSwimIdRouteImport } from './routes/swim.$swimId'
import { Route as AuthenticatedSwimSwimIdEditRouteImport } from './routes/_authenticated/swim.$swimId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SwimSwimIdRoute = SwimSwimIdRouteImport.update({
  id: '/swim/$swimId',
  path: '/swim/$swimId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSwimSwimIdEditRoute =
  AuthenticatedSwimSwimIdEditRouteImport.update({
    id: '/swim/$swimId/edit',
    path: '/swim/$swimId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof AuthenticatedNewRoute
  '/swim/$swimId': typeof SwimSwimIdRoute
  '/swim/$swimId/edit': typeof AuthenticatedSwimSwimIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof AuthenticatedNewRoute
  '/swim/$swimId': typeof SwimSwimIdRoute
  '/swim/$swimId/edit': typeof AuthenticatedSwimSwimIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/swim/$swimId': typeof SwimSwimIdRoute
  '/_authenticated/swim/$swimId/edit': typeof AuthenticatedSwimSwimIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/new' | '/swim/$swimId' | '/swim/$swimId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/new' | '/swim/$swimId' | '/swim/$swimId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/new'
    | '/swim/$swimId'
    | '/_authenticated/swim/$swimId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SwimSwimIdRoute: typeof SwimSwimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/swim/$swimId': {
      id: '/swim/$swimId'
      path: '/swim/$swimId'
      fullPath: '/swim/$swimId'
      preLoaderRoute: typeof SwimSwimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/swim/$swimId/edit': {
      id: '/_authenticated/swim/$swimId/edit'
      path: '/swim/$swimId/edit'
      fullPath: '/swim/$swimId/edit'
      preLoaderRoute: typeof AuthenticatedSwimSwimIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedSwimSwimIdEditRoute: typeof AuthenticatedSwimSwimIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedSwimSwimIdEditRoute: AuthenticatedSwimSwimIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SwimSwimIdRoute: SwimSwimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
